HCApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HCApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult LoginCustomer()
        {
            return View();
        }

        public ActionResult LoginScheduler()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "HelpCentral Application";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact the Software Team at CPSC 362";

            return View();
        }
    }
}

HCApp/Controllers/customersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HCApp;
using HCApp.Models;

namespace HCApp.Controllers
{
    public class customersController : Controller
    {
        private helpcentraldbEntities db = new helpcentraldbEntities();

        [HttpPost]
        public ActionResult Login(customer c)
        {
            string actionAfterLogin = "LoginBad"; //this logs in
            ViewResult vr = View(actionAfterLogin);

            if (ModelState.IsValid)
            {
                var customerList = db.customers.ToList();

                var userToLogin = db.customers.Where(i => (i.email == c.email) && (i.password == c.password)).FirstOrDefault();

                if (userToLogin != null)
                {
                    var orderList = db.orders.Where(i => i.customerid == userToLogin.customerid).ToList();
                    var customerVM = new CustomerViewModel() { Customer = userToLogin, OrderList = orderList};
                    actionAfterLogin = "LoginGood";
                    vr = View(actionAfterLogin, customerVM);
                }
            }

            return vr;
        }

        // GET: customers
        public ActionResult Index()
        {
            return View(db.customers.ToList());
        }

        // GET: customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "customerid,persontypeid,name,email,gender,address,phone")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "customerid,persontypeid,name,email,gender,address,phone")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            customer customer = db.customers.Find(id);
            db.customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HCApp/Controllers/schedulersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HCApp;
using HCApp.Models;

namespace HCApp.Controllers
{
    public class schedulersController : Controller
    {
        private helpcentraldbEntities db = new helpcentraldbEntities();

        [HttpPost]
        public ActionResult Login(scheduler s)
        {
            string actionAfterLogin = "LoginBad";
            ViewResult vr = View(actionAfterLogin);

            if (ModelState.IsValid)
            {
                var customerList = db.customers.ToList();
                var genieList = db.genies.ToList();

                var userToLogin = db.schedulers.Where(i => (i.email == s.email) && (i.password == s.password)).FirstOrDefault();

                if (userToLogin != null)
                {
                    List<CustomerViewModel> temp1 = new List<CustomerViewModel>();
                    List<GenieViewModel> temp2 = new List<GenieViewModel>();
                    foreach (var item in customerList)
                    {
                        var orderarray = db.orders.Where(i => i.customerid == item.customerid).ToList();
                        temp1.Add(new CustomerViewModel() { Customer = item, OrderList = orderarray });
                    }
                    foreach (var item1 in genieList)
                    {
                        var array = db.workrequests.Where(i => i.genieid == item1.genieid).ToList();
                        temp2.Add(new GenieViewModel() { Genie = item1, WorkRequestList = array});
                    }
                    actionAfterLogin = "LoginGood";
                    var finalview = new SchedulerViewModel() { CustomerViewModelList = temp1, GenieViewModelList = temp2};
                    vr = View(actionAfterLogin,finalview);
                }
            }

            return vr;
        }
        // GET: schedulers
        public ActionResult Index()
        {
            return View();
        }
        // GET: customers/Details/5
        public ActionResult Details1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult Details2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order or = db.orders.Find(id);
            if (or == null)
            {
                return HttpNotFound();
            }
            return View(or);
        }
        public ActionResult GenieDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           genie gen = db.genies.Find(id);
            if (gen == null)
            {
                return HttpNotFound();
            }
            return View(gen);
        }

    }
}

HCApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>HelpCentral Application a cool app.</p>

HCApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@helpcentral.com">Support@helpcentral.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@helpcentral.com">Marketing@helpcentral.com</a>
</address>

HCApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "HelpCentral Application Home Page";
}

<div class="jumbotron">
    <h1>HelpCentral Application</h1>
    <p class="lead">HelpCentral Application is a free application designed to bring together people with Genies who can help them with all sorts of stuff like walking the dog or helping with the chemestry homework.</p>
</div>

HCApp/Views/Home/Login.cshtml
@model HCApp.customer

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "customers", FormMethod.Post))
{
    <table>
        <tr>
            <td>email:</td>
            <td>@Html.TextBoxFor(i => i.email)</td>
        </tr>
        <tr>
            <td>password:</td>
            <td>@Html.TextBoxFor(i => i.password)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Login" />
            </td>
        </tr>
    </table>


}

HCApp/Views/Home/LoginCustomer.cshtml
@model HCApp.customer

@{
    ViewBag.Title = "Login Customer";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "customers", FormMethod.Post))
{
    <table class="loginview">
        <tr>
            <td>email:</td>
            <td>@Html.TextBoxFor(i => i.email)</td>
        </tr>
        <tr>
            <td>password:</td>
            <td>@Html.PasswordFor(i => i.password)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Login" />
            </td>
        </tr>
    </table>
}

HCApp/Views/Home/LoginScheduler.cshtml
@model HCApp.customer

@{
    ViewBag.Title = "Login Scheuler";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "schedulers", FormMethod.Post))
{
    <table class="loginview" >
        <tr>
            <td>email:</td>
            <td>@Html.TextBoxFor(i => i.email)</td>
        </tr>
        <tr>
            <td>password:</td>
            <td>@Html.PasswordFor(i => i.password)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Login" />
            </td>
        </tr>
    </table>


}