HCApp/Models/SchedulerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HCApp.Models
{
    public class SchedulerViewModel
    {
        public List<CustomerViewModel> CustomerViewModelList { get; set; }
        public List<GenieViewModel> GenieViewModelList { get; set; } 
    }
}

HCApp/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HCApp;

namespace HCApp.Controllers
{
    public class ordersController : Controller
    {
        private helpcentraldbEntities db = new helpcentraldbEntities();

        // GET: orders
        public ActionResult Index()
        {
            return View(db.orders.ToList());
        }

        // GET: orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order order = db.orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

    
        // GET: orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "orderid,servicetypeid,orderstatusid,customerid,estimatedhours,actualhours,perferredgenieid,specialrequest,dateplaced,datecompleted,price")] order order)
        {
            if (ModelState.IsValid)
            {
                db.orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order order = db.orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "orderid,servicetypeid,orderstatusid,customerid,estimatedhours,actualhours,perferredgenieid,specialrequest,dateplaced,datecompleted,price")] order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order order = db.orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            order order = db.orders.Find(id);
            db.orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HCApp/Controllers/schedulersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HCApp;
using HCApp.Models;

namespace HCApp.Controllers
{
    public class schedulersController : Controller
    {
        private helpcentraldbEntities db = new helpcentraldbEntities();

        [HttpPost]
        public ActionResult Login(scheduler s)
        {
            string actionAfterLogin = "LoginBad";
            ViewResult vr = View(actionAfterLogin);

            if (ModelState.IsValid)
            {
                var customerList = db.customers.ToList();
                var genieList = db.genies.ToList();

                var userToLogin = db.schedulers.Where(i => (i.email == s.email) && (i.password == s.password)).FirstOrDefault();

                if (userToLogin != null)
                {
                    List<CustomerViewModel> temp1 = new List<CustomerViewModel>();
                    List<GenieViewModel> temp2 = new List<GenieViewModel>();
                    foreach (var item in customerList)
                    {
                        var orderarray = db.orders.Where(i => i.customerid == item.customerid).ToList();
                        temp1.Add(new CustomerViewModel() { Customer = item, OrderList = orderarray });
                    }
                    foreach (var item1 in genieList)
                    {
                        var array = db.workrequests.Where(i => i.genieid == item1.genieid).ToList();
                        temp2.Add(new GenieViewModel() { Genie = item1, WorkRequestList = array});
                    }
                    actionAfterLogin = "LoginGood";
                    var finalview = new SchedulerViewModel() { CustomerViewModelList = temp1, GenieViewModelList = temp2};
                    vr = View(actionAfterLogin,finalview);
                }
            }

            return vr;
        }
        // GET: schedulers
        public ActionResult Index()
        {
            return View();
        }
        // GET: customers/Details/5
        public ActionResult Details1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        public ActionResult Details2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order or = db.orders.Find(id);
            if (or == null)
            {
                return HttpNotFound();
            }
            return View(or);
        }
        public ActionResult GenieDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           genie gen = db.genies.Find(id);
            if (gen == null)
            {
                return HttpNotFound();
            }
            return View(gen);
        }

    }
}

HCApp/Views/schedulers/Details1.cshtml
@model HCApp.customer

@{
    ViewBag.Title = "Details1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.persontypeid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persontypeid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

    </dl>
</div>

HCApp/Views/schedulers/Details2.cshtml
@model HCApp.order

@{
    ViewBag.Title = "Details2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Order Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.servicetypeid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.servicetypeid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.orderstatusid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.orderstatusid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.customerid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.customerid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estimatedhours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estimatedhours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actualhours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actualhours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.perferredgenieid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.perferredgenieid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.specialrequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.specialrequest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateplaced)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateplaced)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datecompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datecompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pricepaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pricepaid)
        </dd>

    </dl>
</div>

HCApp/Views/schedulers/GenieDetails.cshtml
@model HCApp.genie

@{
    ViewBag.Title = "GenieDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Genie Details</h2>

<div>
    <h4>Genie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.genieid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genieid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.persontypeid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persontypeid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

    </dl>
</div>

HCApp/Views/schedulers/LoginBad.cshtml
@{
    ViewBag.Title = "LoginBad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LoginBad</h2>

<h3>Problem with the scheduler login!!!!.</h3>

HCApp/Views/schedulers/LoginGood.cshtml
@Model HCApp.SchedulerViewModel


@{
    ViewBag.Title = "LoginGood";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Scheduler View</h2>

<h3>Customer Orders</h3>

<table class="scheduler_table_one">
    <tr>
        <th>Customer</th>
        <th>Order(s)</th>
    </tr>
    @foreach (var item in Model.CustomerViewModelList)
    {
        <tr>
            <td>@Html.ActionLink((string)@item.Customer.name, "Details1", new { id = item.Customer.customerid })</td>
            <td>
                @foreach (var second in item.OrderList)
                { 
                    @Html.ActionLink("order:" + (String)(@second.orderid).ToString(), "Details", "orders", new { id = second.orderid }, null)  
                    <br/>               
                }
            </td>
        </tr>
    }
</table>

<h3>Genie Work Requests</h3>
   
    @foreach (var item2 in Model.GenieViewModelList)
    {
        <table class="scheduler_table_one">
            <tr>
                <td>@Html.ActionLink((string)@item2.Genie.name, "GenieDetails", new { id = item2.Genie.genieid })</td>
            </tr>
            <tr>
                <th>Genie ID</th>
                <th>Work Request ID</th>
                <th>Request Type ID</th>
                <th>Service Type ID</th>
                <th>Schedule ID</th>
            </tr>
            @foreach (var item3 in item2.WorkRequestList)
            {
                <tr>
                    <td>@item3.genieid</td>
                    <td>@item3.workrequestid</td>
                    <td>@item3.requesttypeid</td>
                    <td>@item3.servicetypelistid</td>
                    <td>@item3.scheduleid</td>
                </tr>
            }
        </table>
    }
       